title: Our XR3ngine Helm chart repo
description: A chart repo for storing charts.
theme: minima
url: "https://social.xrengine.io"
repo_name: xr3ngine

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore