title: Our XR3ngine Helm chart repo
description: A chart repo for storing charts.
theme: minima
url: "https://xr3ngine.github.io/xrsocial-ops/"
repo_name: xrsocial

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore