title: Our xrchat Helm chart repo
description: A chart repo for storing charts.
theme: minima
url: "https://xrchat.github.io/xrchat-ops/"
repo_name: xrchat

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore